name: Apply terraform

on: 
  workflow_call:
    secrets:
      PROD_CP_GCP_PROJECT_ID:
        required: true
      DEV_CP_GCP_PROJECT_ID:
        required: true
      DEVOPS_ACCESS_REPO_TOKEN:
        required: true
      PROD_CP_GCP_SVC_GITHUB_RUNNER_KEY_FILE:
        required: true
      DEV_CP_GCP_SVC_GITHUB_RUNNER_KEY_FILE:
        required: true
    inputs:
      TEST:
        type: boolean
        default: false
        required: false
        description: 'A flag to determine whether to apply testing envionment.'
    outputs:
      TEST_ENDPOINT:
        value: ${{ jobs.apply_terraform.outputs.TEST_ENDPOINT }}
        description: "The endpoint that used for integration test."

jobs:
  apply_terraform:
    runs-on: ubuntu-latest
    outputs:
      TEST_ENDPOINT: ${{ steps.terraform_output.outputs.test_endpoint }}
    steps:
      - uses: actions/checkout@main

      - name: Export environments
        run: |
          if [ ${{ inputs.TEST }} ]; then
            REPOSITORY="test-${GITHUB_REPOSITORY##*/}"
          else
            REPOSITORY=${GITHUB_REPOSITORY##*/}
          fi

          if [[ "$REF" =~ ^[0-9]+.[0-9]+.[0-9]+$ || $GITHUB_REF_NAME == "master" ]]; then
            GCP_ENV=production
            GCP_PROJECT_ID=${{ secrets.PROD_CP_GCP_PROJECT_ID }}
            INFRA_BRANCH=master
          else
            GCP_ENV=develop
            GCP_PROJECT_ID=${{ secrets.DEV_CP_GCP_PROJECT_ID }}
            INFRA_BRANCH=develop
          fi

          echo "node version: `node -v`"

          cat <<- EOF >> ${GITHUB_ENV}
          REPOSITORY=${REPOSITORY}
          GCP_ENV=${GCP_ENV}
          GCP_PROJECT_ID=${GCP_PROJECT_ID}
          INFRA_BRANCH=${INFRA_BRANCH}
          INFRA_REPO=CoolBitX-Technology/cp-platform-infrastructure
          INFRA_DIR=${GITHUB_WORKSPACE}/_infra
          EOF

      - name: Checkout infra
        uses: actions/checkout@main
        with:
          repository: ${{ env.INFRA_REPO }}
          path: ${{ env.INFRA_DIR }}
          ref: ${{ env.INFRA_BRANCH }}
          token: ${{ secrets.DEVOPS_ACCESS_REPO_TOKEN }}

      - name: Authenticate gcloud
        if: ${{ env.GCP_ENV == 'production' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.PROD_CP_GCP_SVC_GITHUB_RUNNER_KEY_FILE }}

      - name: Authenticate gcloud
        if: ${{ env.GCP_ENV == 'develop' }}
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.DEV_CP_GCP_SVC_GITHUB_RUNNER_KEY_FILE }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.x

      - name: Terraform init
        working-directory: ${{ env.INFRA_DIR }}/terraform
        run: |
          terraform init -backend-config=bucket=${GCP_PROJECT_ID}-terraform-state

      - name: Terraform apply
        working-directory: ${{ env.INFRA_DIR }}/terraform
        run: |
          terraform apply -auto-approve -var=env=${GCP_ENV} -var=testing=${{ inputs.TEST }} -target=module.${REPOSITORY}

      - name: Terraform output
        id: terraform_output
        working-directory: ${{ env.INFRA_DIR }}/terraform
        run: |
          # Raw output will be 
          # [command]/home/runner/work/_temp/65a07e07-0121-4063-a24e-ed1ad76a5099/terraform-bin output test-cp-launchpad-api-endpoint launchpad.api.test-wallet.cbx.io ::debug::Terraform exited with code 0. ::debug::stdout: launchpad.api.test-wallet.cbx.io%0A ::debug::stderr:  ::debug::exitcode: 0 
          test_endpoint=$(terraform output -raw ${REPOSITORY}-endpoint | tr '\n' ' ' | awk '{print $5}' | awk -F':' '{print $1}')

          echo "test_endpoint=$test_endpoint" >> "$GITHUB_OUTPUT"
        if: ${{ inputs.TEST }}