name: Assign Reviewers

on: 
  pull_request:
    types: 
      [ready_for_review, opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers to PR
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
