name: Run integration test

on: 
  workflow_call:
    inputs:
      OWNER_SLACK_ID:
        type: string
        required: true
      SERVICE:
        type: string
        required: true
      TEST_ENDPOINT:
        type: string
        default: ""
        required: false
      ENVIRONMENT:
        type: string
        default: "dev"
        required: false
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
     
jobs:
  trigger_test:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow dispatch
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          repo: CoolBitX-Technology/api-automation 
          ref: master
          workflow: API Integration Testing
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: >- 
            { 
              "run_id": "${{ github.run_id }}",
              "owner": "${{ inputs.OWNER_SLACK_ID }}", 
              "service": "${{ inputs.SERVICE }}",
              "test_endpoint": "${{ inputs.TEST_ENDPOINT }}",
              "environment": "${{ inputs.ENVIRONMENT }}"
            }

      - name: Get integration workflow id
        run: |
          sleep 10
          workflow_id=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/CoolBitX-Technology/api-automation/actions/workflows/api_integration_testing.yml/runs?page=1&per_page=10" \
              | jq -r '.workflow_runs[] | select(.name == "${{ inputs.ENVIRONMENT }}-${{ inputs.SERVICE }}-${{ github.run_id }}") | .id' | head -n 1
          )

          if [ -z "$workflow_id" ]; then
            echo "No workflow generated" && exit 1 
          fi
          echo "workflow_id=$workflow_id" >> $GITHUB_ENV

      - name: Get integration test status
        run: |
          START_TIME=$(date +%s)
          while [ $(( $(date +%s) - $START_TIME )) -lt 300 ]; do
            status=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/CoolBitX-Technology/api-automation/actions/runs/${{ env.workflow_id }}" | jq -r '.conclusion'
            )  
            echo $status

            if [ $status = "success" ]; then
              echo "API testing finish. Result: Success" && exit 0
            elif [ $status = "failure" ]; then
              echo "API testing finish. Result: Failed" && exit 1 
            fi          
            sleep 20
          done
          echo "API testing didn't finish in 5 minutes" && exit 1
