name: Run integration test

on: 
  workflow_call:
    inputs:
      OWNER_SLACK_ID:
        type: string
        required: true
      SERVICE:
        type: string
        required: true
      TEST_ENDPOINT:
        type: string
        required: true
    secrets:
      PERSONAL_ACCESS_TOKEN:
        required: true
     
jobs:
  trigger_test:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow dispatch
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          repo: CoolBitX-Technology/api-automation 
          ref: master
          workflow: API Integration Testing
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{ "owner": "${{ inputs.OWNER_SLACK_ID }}", "service": "${{ inputs.SERVICE }}", "test_endpoint": "${{ inputs.TEST_ENDPOINT }}" }'
